# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe35a2951d5c6e749ce5f4bdb4b89fad200c6bebb4b4da03d7d269f880ef7d8b8209f55436bb318ad8adb6b70321148b49588db38ed75dc0ebbe39acdbec67a5

test:
  secret_key_base: b6e227fd3afbf6433abd69b0abc55ea5b91c4bfd46b5168afe3ec37e19aee054b6971274aed644b66186bc04fcd1f33eaa9c7b46c886930a01abaf76a4632a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
